package test;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import test.PostingsList.PostingsListElement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author zayda
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        labelMainTitle = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCrawler = new javax.swing.JMenu();
        actionNewCrawling = new javax.swing.JMenuItem();
        actionSeeCrawledSites = new javax.swing.JMenuItem();
        actionDeleteCrawledFiles = new javax.swing.JMenuItem();
        menuIndex = new javax.swing.JMenu();
        actionDeleteIndexFiles = new javax.swing.JMenuItem();
        actionSearch = new javax.swing.JMenu();
        actionNewSearch = new javax.swing.JMenuItem();
        actionAdvancedSearch = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        actionAbout = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelMainTitle.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        labelMainTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        menuCrawler.setText("Crawler");

        actionNewCrawling.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        actionNewCrawling.setText("New crawling");
        actionNewCrawling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionNewCrawlingActionPerformed(evt);
            }
        });
        menuCrawler.add(actionNewCrawling);

        actionSeeCrawledSites.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        actionSeeCrawledSites.setText("View crawled domains");
        actionSeeCrawledSites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionSeeCrawledSitesActionPerformed(evt);
            }
        });
        menuCrawler.add(actionSeeCrawledSites);

        actionDeleteCrawledFiles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        actionDeleteCrawledFiles.setText("Delete generated files");
        actionDeleteCrawledFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionDeleteCrawledFilesActionPerformed(evt);
            }
        });
        menuCrawler.add(actionDeleteCrawledFiles);

        jMenuBar1.add(menuCrawler);

        menuIndex.setText("Index");

        actionDeleteIndexFiles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.CTRL_MASK));
        actionDeleteIndexFiles.setText("Delete index files");
        actionDeleteIndexFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionDeleteIndexFilesActionPerformed(evt);
            }
        });
        menuIndex.add(actionDeleteIndexFiles);

        jMenuBar1.add(menuIndex);

        actionSearch.setText("Search engine");

        actionNewSearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        actionNewSearch.setText("New search");
        actionNewSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionNewSearchActionPerformed(evt);
            }
        });
        actionSearch.add(actionNewSearch);

        actionAdvancedSearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        actionAdvancedSearch.setText("Advanced search");
        actionAdvancedSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionAdvancedSearchActionPerformed(evt);
            }
        });
        actionSearch.add(actionAdvancedSearch);

        jMenuBar1.add(actionSearch);

        menuHelp.setText("Help");

        actionAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        actionAbout.setText("About");
        actionAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionAboutActionPerformed(evt);
            }
        });
        menuHelp.add(actionAbout);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(labelMainTitle)
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(labelMainTitle)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actionSeeCrawledSitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionSeeCrawledSitesActionPerformed
        new CrawledSitesInterface().setVisible(true);
    }//GEN-LAST:event_actionSeeCrawledSitesActionPerformed

    private void actionNewSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionNewSearchActionPerformed
        new SearchInterface().setVisible(true);
    }//GEN-LAST:event_actionNewSearchActionPerformed

    private void actionNewCrawlingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionNewCrawlingActionPerformed
        new CrawlingInterface().setVisible(true);
    }//GEN-LAST:event_actionNewCrawlingActionPerformed

    private void actionDeleteCrawledFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionDeleteCrawledFilesActionPerformed
        new DeleteCrawledFilesInterface().setVisible(true);
    }//GEN-LAST:event_actionDeleteCrawledFilesActionPerformed

    private void actionAdvancedSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionAdvancedSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actionAdvancedSearchActionPerformed

    private void actionAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionAboutActionPerformed
        JOptionPane.showMessageDialog(null,"Créditos a Lyon y Juank :3");
    }//GEN-LAST:event_actionAboutActionPerformed

    private void actionDeleteIndexFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionDeleteIndexFilesActionPerformed
        int confirmation = JOptionPane.showConfirmDialog( null, "Are you sure you want to delete ALL index files?",
                            "Confirm crawling without limit", JOptionPane.YES_NO_OPTION);
        if(confirmation==JOptionPane.YES_OPTION){
            IndexerControler.deleteSerFiles();
            IndexerControler.initialize();
        }
    }//GEN-LAST:event_actionDeleteIndexFilesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new ttstest().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        IndexerControler.initialize();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem actionAbout;
    private javax.swing.JMenuItem actionAdvancedSearch;
    private javax.swing.JMenuItem actionDeleteCrawledFiles;
    private javax.swing.JMenuItem actionDeleteIndexFiles;
    private javax.swing.JMenuItem actionNewCrawling;
    private javax.swing.JMenuItem actionNewSearch;
    private javax.swing.JMenu actionSearch;
    private javax.swing.JMenuItem actionSeeCrawledSites;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelMainTitle;
    private javax.swing.JMenu menuCrawler;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuIndex;
    // End of variables declaration//GEN-END:variables
}
