/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import javax.swing.JOptionPane;


@SuppressWarnings("serial")
public class Interface extends javax.swing.JFrame {

    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        labelMainTitle = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuCrawler = new javax.swing.JMenu();
        actionNewCrawling = new javax.swing.JMenuItem();
        actionSeeCrawledSites = new javax.swing.JMenuItem();
        menuDeleteCrawledFiles = new javax.swing.JMenuItem();
        menuSearch = new javax.swing.JMenu();
        actionNewSearch = new javax.swing.JMenuItem();
        actionPersonalizedSearch = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        actionSeeHelp = new javax.swing.JMenuItem();
        actionSeeAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelMainTitle.setText("Best search engine ever.");

        menuCrawler.setText("Crawler");

        actionNewCrawling.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        actionNewCrawling.setText("New crawling");
        actionNewCrawling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionNewCrawlingActionPerformed(evt);
            }
        });
        menuCrawler.add(actionNewCrawling);

        actionSeeCrawledSites.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        actionSeeCrawledSites.setText("View crawled domains");
        menuCrawler.add(actionSeeCrawledSites);

        menuDeleteCrawledFiles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        menuDeleteCrawledFiles.setText("Delete generated files");
        menuDeleteCrawledFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeleteCrawledFilesActionPerformed(evt);
            }
        });
        menuCrawler.add(menuDeleteCrawledFiles);

        menuBar.add(menuCrawler);

        menuSearch.setText("Buscador");

        actionNewSearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        actionNewSearch.setText("New search");
        actionNewSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionNewSearchActionPerformed(evt);
            }
        });
        menuSearch.add(actionNewSearch);

        actionPersonalizedSearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        actionPersonalizedSearch.setText("Advanced search");
        actionPersonalizedSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPersonalizedSearchActionPerformed(evt);
            }
        });
        menuSearch.add(actionPersonalizedSearch);

        menuBar.add(menuSearch);

        menuHelp.setText("Ayuda");

        actionSeeHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        actionSeeHelp.setText("See hotkeys");
        actionSeeHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionSeeHelpActionPerformed(evt);
            }
        });
        menuHelp.add(actionSeeHelp);

        actionSeeAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        actionSeeAbout.setText("About");
        actionSeeAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionSeeAboutActionPerformed(evt);
            }
        });
        menuHelp.add(actionSeeAbout);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(labelMainTitle)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(labelMainTitle)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actionNewSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionNewSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actionNewSearchActionPerformed

    private void actionSeeAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionSeeAboutActionPerformed
        JOptionPane.showMessageDialog(null,"Créditos a Lyon y Juank :3");
    }//GEN-LAST:event_actionSeeAboutActionPerformed

    private void actionNewCrawlingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionNewCrawlingActionPerformed
        new CrawlingInterface().setVisible(true);
    }//GEN-LAST:event_actionNewCrawlingActionPerformed

    private void menuDeleteCrawledFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeleteCrawledFilesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDeleteCrawledFilesActionPerformed

    private void actionPersonalizedSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPersonalizedSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actionPersonalizedSearchActionPerformed

    private void actionSeeHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionSeeHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actionSeeHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem actionNewCrawling;
    private javax.swing.JMenuItem actionNewSearch;
    private javax.swing.JMenuItem actionPersonalizedSearch;
    private javax.swing.JMenuItem actionSeeAbout;
    private javax.swing.JMenuItem actionSeeCrawledSites;
    private javax.swing.JMenuItem actionSeeHelp;
    private javax.swing.JLabel labelMainTitle;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCrawler;
    private javax.swing.JMenuItem menuDeleteCrawledFiles;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuSearch;
    // End of variables declaration//GEN-END:variables
}
